### ISSUE TITLE
Client library in Ruby

### ISSUE THREAD

**Issue by LeKristapino** [SK-EID/smart-id-documentation#10]
Hi, 

Just wanted to let you know that we've created a client library for Smart ID in ruby. Implementing all the security needs you requested in your documentation. Although it only supports authentication (as there was no need, we have not looked into signing functionality).

Feel free to add it to your client library list. https://github.com/zippyvision/smart-id-ruby

**Comment by jalukse** [comment]
Thank you.
Added to https://github.com/SK-EID/smart-id-documentation/wiki/Client-libraries
