### ISSUE TITLE
Test account 010101-10006 auto confirmation doesn't work

### ISSUE THREAD

**Issue by EdgarsM** [SK-EID/smart-id-documentation#12]
Test account 010101-10006 that can be used for automated testing stopped to auto confirm requests today.
Java library times out on waiting confirmation:

`ee.sk.smartid.exception.SessionTimeoutException: null at ee.sk.smartid.SmartIdRequestBuilder.validateSessionResult(SmartIdRequestBuilder.java:181) at ee.sk.smartid.AuthenticationRequestBuilder.validateAuthenticationResponse(AuthenticationRequestBuilder.java:412) at ee.sk.smartid.AuthenticationRequestBuilder.createSmartIdAuthenticationResponse(AuthenticationRequestBuilder.java:380) at app.klix.auth.gateway.smartid.SmartIdGateway.authenticate(SmartIdGateway.java:115) at app.klix.auth.gateway.smartid.SmartIdGateway.lambda$initAuthentication$0(SmartIdGateway.java:93) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:835)`

**Comment by jalukse** [comment]
Mock is up again
