### ISSUE TITLE
Demo SmartIDs giving 471

### ISSUE THREAD

**Issue by alex-nikitin-enlabs** [SK-EID/smart-id-documentation#14]
Hi! Thank you for your work! 
Could you please verify that test smartIDs are still active?
Tried: 
EE 10101010005
LV 010101-10006
LT 10101020001
Using Curl to verify:
```
curl --header "Content-Type: application/json" \
  --data '{
   "relyingPartyUUID": "00000000-0000-0000-0000-000000000000",
   "relyingPartyName": "DEMO",
   "hash": "FfXZHTHsNCQ9yw7e/5nJyxFqkrgkg3rtJarp/uthExU=",
   "hashType": "SHA256",
   "displayText": "Testing Smart-ID"
   }' \
  https://sid.demo.sk.ee/smart-id-rp/v1/authentication/pno/EE/10101010005
```
Responce:
`{"code":471,"message":"No suitable account found"}`

**Comment by jalukse** [comment]
These numbers are not working anymore. 
Please use new numbers from https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters#test-accounts-for-automated-testing
