### ISSUE TITLE
Certificate pinning and future certs

### ISSUE THREAD

**Issue by jimmytheneutrino** [SK-EID/smart-id-documentation#15]
In order to avoid downtime after the change of SSL certificates of RP API backends, there should be a way to obtain the new certificates beforehand (preferably several months in advance). 
How to do it?
If it is possible, IMHO, it should be described here.

Note that the current rp-api cert expires on November 5 and https://www.skidsolutions.eu/en/repository/certs does not give hints whether the new one is available.

**Comment by jalukse** [comment]
You are absolutely right.
New certificate can be currently found [here](https://github.com/SK-EID/smart-id-documentation/wiki/Implementing-HTTPS-pinning#rp-apismart-idcom-certificates)

Certificate change will be applied on 02.11.2021
