### ISSUE TITLE
Automatically open Smart-ID

### ISSUE THREAD

**Issue by MagnusModig** [SK-EID/smart-id-documentation#16]
Hi

When reading this documentation under  2.2 Relying Party REST interface, it describe the following...

"The Smart-ID server then sends a push message notification to the user's device where the user opens the Smart-ID application, checks the details and enters a PIN code."

Does this mean that the user will need to open up smart-id application by himself or can the smart-id be opened automatically?

**Comment by jalukse** [comment]
Smart-id app will be opened automatically. 
For this to work properly app needs to have correct permissions on phone side . More info [here ](https://www.smart-id.com/help/faq/smart-id-notifications/). In case of some failure (push message is not working or there are some missing permissions) then user should open app manually.
