### ISSUE TITLE
Absence of test account 30303039903

### ISSUE THREAD

**Issue by Alek5andr** [SK-EID/smart-id-documentation#18]
Hi!

After revision e769657 - https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters/e76965759666df9fb05d7e7108e459c1c2d24f47 - test account 30303039903 was deleted.
Please restore it.

**Comment by jalukse** [comment]
Test accounts restored
https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters/bfe1d07b6aa006d024d36ffd8b9eeeee562a22b6
