### ISSUE TITLE
Test accounts have expired certificates

### ISSUE THREAD

**Issue by gregorjohannson** [SK-EID/smart-id-documentation#3]
The expired certificates of test accounts cause unexpected errors when using DigiDoc4j.
Signature creation with DigiDoc4j throws DSSException instead of expected SmartIdException (due to use of DigiDoc4j SignatureBuilder, which gets called before SmartIdSignature.sign()).

For example, testing signature creation with test accounts 10101010016 & 10101010027 should throw UserRefusedException and SessionTimeoutException respectively, but the expired certificates of the accounts throw eu.europa.esig.dss.DSSException.

Solution would be to renew the certificates of provided test accounts.

**Comment by thedevdevil** [comment]
I'm stuck on this issue, too. How to get past this?

**Comment by jalukse** [comment]
I made some fixes to OCSP. Certificates are now valid and ocsp is responding good. You should check which OCSP are you using.
```
$ openssl ocsp -issuer test_of_eid16.crt.cer -serial 0x70f8be1b97064e3f5c87d4ce771516a8 -url http://demo.sk.ee/ocsp -noverify
0x70f8be1b97064e3f5c87d4ce771516a8: good
        This Update: Aug  9 14:04:28 2019 GMT
$ openssl ocsp -issuer test_of_eid16.crt.cer -serial 0x1818824369224f0f5ca1e86eda85bea1 -url http://demo.sk.ee/ocsp -noverify
0x1818824369224f0f5ca1e86eda85bea1: good
        This Update: Aug  9 14:05:11 2019 GMT
$ openssl ocsp -issuer test_of_eid16.crt.cer -serial 0x1d0a27ad64d827bb59a6ab61b0f77adb -url http://demo.sk.ee/ocsp -noverify
0x1d0a27ad64d827bb59a6ab61b0f77adb: good
        This Update: Aug  9 14:24:07 2019 GMT
```
