### ISSUE TITLE
One test account has a broken identity number

### ISSUE THREAD

**Issue by keenjus** [SK-EID/smart-id-documentation#4]
Seems like one of the specified automated test accounts has wrong info [here](https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters#accounts)

![image](https://user-images.githubusercontent.com/8611102/52774574-2fd76500-3046-11e9-9c14-94e3084ef3ad.png)

NationalIdentityNumber is specified as "010101-1001" but looking at its DocumentNumber "PNOLV-010101-10014-782V-Q", I see that it should actually be "010101-10014".

Found this by writing some tests and that account seems to be the only one failing

**Comment by jalukse** [comment]
fixed
