### ISSUE TITLE
Unexpected timeouts in DEMO environment

### ISSUE THREAD

**Issue by mrts** [SK-EID/smart-id-documentation#9]
According to [*Environment technical parameters*](https://github.com/SK-EID/smart-id-documentation/wiki/Environment-technical-parameters), using national identity number 10101010005 during authentication request should result in `"endResult": "OK"` in session status query in DEMO environment. This was indeed working when I tested in September.

However, currently it results in a timeout instead (using [httpie](https://httpie.org/)):

```bash
$ SESSIONID=$(http POST \
    https://sid.demo.sk.ee/smart-id-rp/v1/authentication/pno/EE/10101010005 \
        relyingPartyUUID=00000000-0000-0000-0000-000000000000 \
        relyingPartyName=DEMO \
        hash=FfXZHTHsNCQ9yw7e/5nJyxFqkrgkg3rtJarp/uthExU= \
        hashType=SHA256 \
        displayText=Testing \
    | grep -oP 'sessionID":"\K[\w-]+')

$ echo $SESSIONID 
685df7c2-1440-4bdc-b5a1-e767c8dfb0e6

$ http https://sid.demo.sk.ee/smart-id-rp/v1/session/${SESSIONID}
http: error: Request timed out (30s).

$ http https://sid.demo.sk.ee/smart-id-rp/v1/session/${SESSIONID}
http: error: Request timed out (30s).

$ http https://sid.demo.sk.ee/smart-id-rp/v1/session/${SESSIONID}
HTTP/1.1 200 
{
    "result": {
        "endResult": "TIMEOUT"
    },
    "state": "COMPLETE"
}
```

**Comment by LoneEngineer** [comment]
Hi, all.

Happy New Year, but Demo environment is failing with the 'timeout exception' since at least 30.12.2019.
Today, the test OCSP also stopped to work.

**Comment by LoneEngineer** [comment]
Working for me today. Thanks.

**Comment by alvar-sk** [comment]
Moc service was down, should be working now again. Closing issue.

**Comment by mrts** [comment]
Thanks, it's working well now. Happy new year :)!
